"""
Django settings for A project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1k1@skr&pi-dld510cjuv@z)cn+_-fc_@6(=3fzzk5fx+4z2!7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',
    'home.apps.HomeConfig',
    'storages',
    'celery',
    'django-celery-beat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'A.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'A.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'                                #static file haye har app bayad too ye file bashan be sme static
STATICFILES_DIRS= [
    BASE_DIR / 'static'                               #static file hayi ke marboot be appe khasi nistan
]




#media files
MEDIA_URL ='/media/'                  #vaghti ye slash ghable media gozashte yani aval boro toooye root e barname bad media. in url eshe jai ke bayad donbaleshon begardim

MEDIA_ROOT = BASE_DIR / 'media'       #pooshei ke tosh save mishan media hayi ke karbaran upload mikonan va itm balai adrese in poshe ast

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'accounts.User'


#arvan storage
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",                              #I COPIED IT FROM DJANGO-STORAGE AMAZON S3 DOCUMENTATIONS.
        "OPTIONS": {
        },
    },
        "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",       #THIS IS A DEFAULT SETTING WHICH MEANS YOU DONT WANT YOUR STATIC FILES TO BE UPLOADED INTO CLOUD STORAGE.
}                                                                                 #I COPY AND PASTE IT FROM DJANGO OFFICIAL WEBSITE DOCUMENTATION 
}
AWS_ACCESS_KEY_ID= 'ff0faf16-9899-4718-b2b8-1823ef9495ee'
AWS_SECRET_ACCESS_KEY= '22d6a3f92d87d2738085390f4f49a0e7647253ad222991da63067aaabc435ffd'
AWS_STORAGE_BUCKET_NAME= 'ghazalmua2'
AWS_SERVICE_NAME='s3'
AWS_S3_FILE_OVERWRITE= False
AWS_S3_ENDPOINT_URL='https://s3.ir-tbz-sh1.arvanstorage.ir/'
AWS_LOCAL_STORAGE= f'{BASE_DIR}/aws/'                                #this means in the root of project(where manage.py located) you have a folder (aws) that download file (from bucket)will go there.

{
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObjectAcl",
                "s3:GetObject", 
                "s3:ListBucket",
                "s3:DeleteObject",
                "s3:PutObjectAcl"

            ],
            "Resource": [
                "arn:aws:s3:::ghazalmua2/*",
                "arn:aws:s3:::ghazalmua2"
            ]
        }
        